<?php

declare(strict_types=1);

namespace TechnoBureau\User\Repository;

use Data\Entity\OAuthClient;
use League\OAuth2\Server as OAuth;

/**
 * OauthClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OauthClientsRepository extends \Doctrine\ORM\EntityRepository implements OAuth\Repositories\ClientRepositoryInterface
{
    public function getClientEntity($clientIdentifier): ?OAuth\Entities\ClientEntityInterface
    {
        /** @var ?OAuthClient */
        return $this->findOneBy(['name' => $clientIdentifier]);
    }

    public function validateClient($clientIdentifier, $clientSecret, $grantType): bool
    {
        $client = $this->getClientEntity($clientIdentifier);

        if (null === $client) {
            return false;
        }

        if (!$this->isGranted($client, $grantType)) {
            return false;
        }

        /** @psalm-suppress UndefinedInterfaceMethod */
        if (empty($client->getSecret())) {
            return false;
        }

        /**
         * @psalm-suppress UndefinedInterfaceMethod
         * @psalm-suppress MixedArgument
         */
        return password_verify((string)$clientSecret, $client->getSecret());
    }

    /** @psalm-suppress UnusedParam */
    private function isGranted(OAuth\Entities\ClientEntityInterface $client, string $grantType = null): bool
    {
        return match ($grantType) {
            null, 'client_credentials', 'authorization_code', 'refresh_token' => true,
            default => false,
        };
    }

}
