<?php

declare(strict_types=1);

namespace TechnoBureau\User\Repository;

use TechnoBureau\User\Entity\OAuthScope;
use Doctrine\ORM\EntityRepository;
use League\OAuth2\Server as OAuth;

/**
 * OauthScopesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OauthScopesRepository extends \Doctrine\ORM\EntityRepository implements OAuth\Repositories\ScopeRepositoryInterface
{
  public function getScopeEntityByIdentifier($identifier): ?OAuth\Entities\ScopeEntityInterface
    {
        /** @var ?OAuthScope $scope */
        $scope = $this->findOneBy(['scope' => $identifier]);

        return $scope;
    }

    public function finalizeScopes(
        array $scopes,
        $grantType,
        OAuth\Entities\ClientEntityInterface $clientEntity,
        $userIdentifier = null
    ): array {
        return $scopes;
    }
}
