<?php
$this->headLink()
    ->prependStylesheet('/css/technobureau.css');
$this->inlineScript()
    ->prependFile('/js/manifest.js')
    ->prependFile('/js/vendor.js')
    ->prependFile('/js/technobureau.js');
?>
<!DOCTYPE html>
<html lang="en">
  <!-- For RTL verison -->
  <!-- <html lang="en" dir="rtl"> -->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Primary Meta Tags -->
    <title><?=$this->headTitle()->renderTitle()?> | TechnoBureau</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="<?=$this->headTitle()->renderTitle()?> | TechnoBureau">
    <meta name="author" content="Ganapathi Chidambaram">
    <link rel="shortcut icon" href="/img/favicon.ico" />
    <meta name="description" content="We are here to share our knowledge through technical articles in a easiest way and also will provide DevOps Tools, Technology News and other debate about various technologies.">
    <meta name="keywords" content="technobureau,admin,templates,mezzio,lightweightframework,microservices,tutorials,linux,tools,linux-tools" />
    <meta name="theme-color" content="#590C12"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="apple-touch-icon" href="/img/apple-touch-icon-192x192.png">
    <link rel="manifest" type="application/manifest+json" href="/manifest.webmanifest">

    <!-- <meta name="color-scheme" content="dark light"> -->
    <!-- OPTIONAL LINKS -->

    <!-- Google Font: Source Sans Pro -->
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> -->

    <!-- Theme style -->
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
  </head>
  <body class="layout-fixed">
  <!-- <body class="hold-transition layout-top-nav" style="height: auto;"> -->
  <!-- <body class="sidebar-mini layout-navbar-fixed"> -->
    <div class="wrapper">
      <!-- Navbar -->
      <nav class="main-header navbar navbar-expand navbar-light">
        <div class="container-fluid">

          <!-- Start navbar links -->
          <ul class="navbar-nav">

            <li class="nav-item">
              <a class="pushmenu nav-link" data-lte-toggle="sidebar-full" href="javascript:;" role="button">
                  <span class="navbar-toggler-icon"></span>
              </a>
            </li>

            <li class="nav-item d-none d-md-block">
              <a href="<?=$this->url('home.view')?>" class="nav-link">Home</a>
            </li>
            <?php if ($this->isGranted('admin.view')) : ?>
                <li class="nav-item d-none d-md-block">
                    <a class="nav-link" href="<?=$this->url('admin.view')?>" >
                        Admin
                    </a>
                </li>
            <?php endif; ?>
            <li class="nav-item d-none d-md-block">
              <a href="#" class="nav-link">Contact</a>
            </li>

          </ul>
          <!-- End navbar links -->

          <ul class="navbar-nav ms-auto">

          <?php if ($this->getRole() !== 'guest') : ?>
            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
              <a class="nav-link" data-bs-toggle="dropdown" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-text" viewBox="0 0 16 16">
                <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
                <path d="M4 5.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zM4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8zm0 2.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z"/>
              </svg>
                <span class="badge bg-danger navbar-badge">3</span>
              </a>
              <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
                <a href="#" class="dropdown-item">
                  <!-- Message Start -->
                  <div class="d-flex">
                    <div class="flex-grow-1">
                      <h3 class="dropdown-item-title">
                        Brad Diesel
                        <span class="float-end fs-7 text-danger"><i class="fas fa-star"></i></span>
                      </h3>
                      <p class="fs-7">Call me whenever you can...</p>
                      <p class="fs-7 text-muted"><i class="far fa-clock me-1"></i> 4 Hours Ago</p>
                    </div>
                  </div>
                  <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                  <!-- Message Start -->
                  <div class="d-flex">
                    <div class="flex-grow-1">
                      <h3 class="dropdown-item-title">
                        John Pierce
                        <span class="float-end fs-7 text-muted"><i class="fas fa-star"></i></span>
                      </h3>
                      <p class="fs-7">I got your message bro</p>
                      <p class="fs-7 text-muted"><i class="far fa-clock me-1"></i> 4 Hours Ago</p>
                    </div>
                  </div>
                  <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                  <!-- Message Start -->
                  <div class="d-flex">
                    <!-- <div class="flex-shrink-0">
                      <img  alt="User Avatar" class="img-size-50 img-circle me-3">
                    </div> -->
                    <div class="flex-grow-1">
                      <h3 class="dropdown-item-title">
                        Nora Silvester
                        <span class="float-end fs-7 text-warning"><i class="fas fa-star"></i></span>
                      </h3>
                      <p class="fs-7">The subject goes here</p>
                      <p class="fs-7 text-muted"><i class="far fa-clock me-1"></i> 4 Hours Ago</p>
                    </div>
                  </div>
                  <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
              </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
              <a class="nav-link" data-bs-toggle="dropdown" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
              </svg>
                <span class="badge bg-warning navbar-badge">15</span>
              </a>
              <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                  <i class="fas fa-envelope me-2"></i> 4 new messages
                  <span class="float-end text-muted fs-7">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                  <i class="fas fa-users me-2"></i> 8 friend requests
                  <span class="float-end text-muted fs-7">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                  <i class="fas fa-file me-2"></i> 3 new reports
                  <span class="float-end text-muted fs-7">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
              </div>
            </li>
            <li class="nav-item dropdown user-menu">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <!-- <img src="./assets/img/user2-160x160.jpg" class="user-image img-circle shadow" alt="User Image"> -->
                <span class="d-none d-md-inline"><?=$this->getDetails()?></span>
              </a>
              <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
                <!-- User image -->
                <li class="user-header bg-primary">
                  <p>
                    <?=$this->getDetails()?>
                    <small>Member since Nov. 2012</small>
                  </p>
                </li>
                <!-- Menu Body -->
                <li class="user-body">
                  <div class="row">
                    <div class="col-4 text-center">
                      <a href="#">Followers</a>
                    </div>
                    <div class="col-4 text-center">
                      <a href="#">Sales</a>
                    </div>
                    <div class="col-4 text-center">
                      <a href="#">Friends</a>
                    </div>
                  </div>
                  <!-- /.row -->
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                  <a href="<?=$this->url('logout.access')?>" class="btn btn-default btn-flat float-end">Sign out</a>
                </li>
              </ul>
            </li>

          <?php endif; ?>
          </ul>
        </div>
      </nav>
      <!-- /.navbar -->

      <!-- Main Sidebar Container -->
      <aside id="navbar-sidebar" class="main-sidebar sidebar-bg-light  elevation-4 collaps">
        <div class="brand-container">
        <a href="<?=$this->url('home.view')?>" class="brand-link">
          <img src="/img/TechnoBureau-text-mini.png" alt="TechnoBureau Logo" class="brand-imag" style=";opacity: .8">
        </a>

        </div>
        <!-- Sidebar -->
        <div class="sidebar">
          <!-- Sidebar Menu -->
          <nav class="mt-2">
            <!-- Sidebar Menu -->
            <ul class="nav nav-pills nav-sidebar flex-column" data-lte-toggle="treeview" role="menu" data-accordion="false">
              <li class="nav-header">MULTI LEVEL EXAMPLE</li>
              <li class="nav-item">
                <a href="javascript:;" class="nav-link">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                  <circle cx="8" cy="8" r="8"/>
                </svg>
                  <p>Level 1</p>

            </a>
              </li>
              <li class="nav-item">
                <a href="javascript:;" class="nav-link">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                  <circle cx="8" cy="8" r="8"/>
                </svg>
                  <p>
                    Level 1
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="end bi bi-chevron-left" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                    </svg>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="javascript:;" class="nav-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                      <circle cx="8" cy="8" r="8"/>
                    </svg>
                      <p>Level 2</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="javascript:;" class="nav-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                      <circle cx="8" cy="8" r="8"/>
                    </svg>
                      <p>
                        Level 2
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="end bi bi-chevron-left" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                        </svg>
                      </p>
                    </a>
                    <ul class="nav nav-treeview">
                      <li class="nav-item">
                        <a href="javascript:;" class="nav-link">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle" viewBox="0 0 16 16">
                          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        </svg>
                          <p>Level 3</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="javascript:;" class="nav-link">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle" viewBox="0 0 16 16">
                          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        </svg>
                          <p>Level 3</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="javascript:;" class="nav-link">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle" viewBox="0 0 16 16">
                          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        </svg>
                          <p>Level 3</p>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a href="javascript:;" class="nav-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                      <circle cx="8" cy="8" r="8"/>
                    </svg>
                      <p>Level 2</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="javascript:;" class="nav-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                      <circle cx="8" cy="8" r="8"/>
                    </svg>
                  <p>Level 1</p>
                </a>
              </li>
              <li class="nav-header">LABELS</li>
              <li class="nav-item">
                <a href="javascript:;" class="nav-link">

                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle text-danger" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                  </svg>
                  <p class="text">Important</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="javascript:;" class="nav-link">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle text-warning" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                  </svg>
                  <p>Warning</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="javascript:;" class="nav-link">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle text-info" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                  </svg>
                  <p>Informational</p>
                </a>
              </li>
            </ul>
          </nav>
        </div>
        <!-- /.sidebar -->
      </aside>
      <!-- Main content -->
      <div class="content-wrapper">
        <div class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <div class="fs-3"><?=$this->headTitle()->renderTitle()?></div>
              </div>
              <div class="col-sm-6">
              <?php if ($this->headTitle()->renderTitle() !== '') : ?>
                <ol class="breadcrumb float-sm-end">
                <?php if ($this->headTitle()->renderTitle() !== 'Home') : ?><li class="breadcrumb-item">
                  <a href="<?=$this->url('home.view')?>">
                    Home
                  </a>
                  </li><?php endif;?>
                  <?php if ($this->headTitle()->renderTitle() !== 'Home') : ?>
                  <li class="breadcrumb-item active" aria-current="page"><?=$this->headTitle()->renderTitle()?></li>
                  <?php endif;?>
                </ol>
                <?php endif;?>
              </div>
            </div>
          </div>
        </div>
        <div class="content">
          <div class="container-fluid">
            <?=$this->content?>

          </div><!-- /.container-fluid -->
        </div>
      </div>
      <!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the end -->
        <!-- <div class="float-end d-none d-sm-inline">
          Anything you want
        </div> -->
        <!-- Default to the start -->
        <strong>Copyright &copy; 2014-<?=date('Y') ?> TechnoBureau</a>.</strong> All rights reserved.
      </footer>

    </div>
    <!--  ./wrapper -->
    <?=$this->inlineScript()?>
  </body>
</html>
