<?php
$this->headLink()
    ->prependStylesheet('/css/technobureau.css');
$this->inlineScript()
    ->prependFile('/js/technobureau.js')
    ->prependFile('https://unpkg.com/vuex@4.0.0-beta.4/dist/vuex.global.prod.js')
    ->prependFile('https://unpkg.com/vue-router@4.0.0-beta.10/dist/vue-router.global.prod.js')
    ->prependFile('https://unpkg.com/vue@3.0.0/dist/vue.global.prod.js')
    ->prependFile('https://code.jquery.com/jquery-3.5.0.min.js');
?>
<!DOCTYPE html>
<html lang="en">
  <!-- For RTL verison -->
  <!-- <html lang="en" dir="rtl"> -->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Primary Meta Tags -->
    <title><?=$this->headTitle()->renderTitle()?> | TechnoBureau</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="<?=$this->headTitle()->renderTitle()?> | TechnoBureau">
    <meta name="author" content="Ganapathi Chidambaram">
    <link rel="shortcut icon" href="/img/favicon.ico" />
    <meta name="description" content="We are here to share our knowledge through technical articles in a easiest way and also will provide DevOps Tools, Technology News and other debate about various technologies.">
    <meta name="keywords" content="technobureau,admin,templates,mezzio,lightweightframework,microservices,tutorials,linux,tools,linux-tools" />
    <meta name="theme-color" content="#590C12"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="apple-touch-icon" href="/img/apple-touch-icon-192x192.png">
    <link rel="manifest" type="application/manifest+json" href="/manifest.webmanifest">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>

    <!-- <meta name="color-scheme" content="dark light"> -->
    <!-- OPTIONAL LINKS -->

    <!-- Google Font: Source Sans Pro -->
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> -->

    <!-- Theme style -->
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
  </head>
<body>
  <!-- This example requires Tailwind CSS v2.0+ -->
<!--
  This example requires updating your template:

  ```
  <html class="h-full bg-gray-100">
  <body class="h-full">
  ```
-->

<div id="app">
<div id="root">

<div class="min-h-full">


  <header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold text-gray-900">Dashboard</h1>
    </div>
  </header>
  <main>
    <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <!-- Replace with your content -->
      <div class="px-4 py-6 sm:px-0">
      <router-view v-slot="{ Component }">
                    <keep-alive>
                        <component :is="Component" />
                    </keep-alive>
                </router-view>
      </div>
      <!-- /End replace -->
    </div>
  </main>
</div>
</div>
</div>
<?=$this->inlineScript()?>
</body>
</html>
